Removing unused workflows

diff --git a/.github/workflows/-master.yml b/.github/workflows/-master.yml
--- a/.github/workflows/-master.yml
+++ b/.github/workflows/-master.yml
@@ -1,113 +1,113 @@
-name: Release Candidate
+# name: Release Candidate
 
-on:
-  push:
-    branches:
-      - "master"
+# on:
+#   push:
+#     branches:
+#       - "master"
 
-jobs:
-  buildMaster:
-    runs-on: ubuntu-latest
+# jobs:
+#   buildMaster:
+#     runs-on: ubuntu-latest
 
-    strategy:
-      matrix:
-        node-version: [20.x]
-        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
+#     strategy:
+#       matrix:
+#         node-version: [20.x]
+#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-      - name: Use Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@v3
-        with:
-          node-version: ${{ matrix.node-version }}
-          cache: "npm"
-      - run: npm ci
-      - name: semver
-        id: semver
-        uses: paulhatch/semantic-version@v4.0.2
-        with:
-          tag_prefix: "v"
-          branch: master
-          major_pattern: "(MAJOR)"
-          minor_pattern: "(MINOR)"
-          format: "${major}.${minor}.${patch}-rc"
-          change_path: "./"
-          bump_each_commit: true
-          namespace: ""
-      - run: |
-          echo "NO CHANGES FOUND";
-          exit 1
-        if: ${{ steps.semver.outputs.changed == 'false' }}
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v3
+#         with:
+#           fetch-depth: 0
+#       - name: Use Node.js ${{ matrix.node-version }}
+#         uses: actions/setup-node@v3
+#         with:
+#           node-version: ${{ matrix.node-version }}
+#           cache: "npm"
+#       - run: npm ci
+#       - name: semver
+#         id: semver
+#         uses: paulhatch/semantic-version@v4.0.2
+#         with:
+#           tag_prefix: "v"
+#           branch: master
+#           major_pattern: "(MAJOR)"
+#           minor_pattern: "(MINOR)"
+#           format: "${major}.${minor}.${patch}-rc"
+#           change_path: "./"
+#           bump_each_commit: true
+#           namespace: ""
+#       - run: |
+#           echo "NO CHANGES FOUND";
+#           exit 1
+#         if: ${{ steps.semver.outputs.changed == 'false' }}
 
-      - run: rm -f ~/.npmrc ; rm -f ./.npmrc ; echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM2_TOKEN_PUB }}" > ./.npmrc
-      - run: |
-          git config user.name "${{ secrets.NPM_NAME }}";
-          git config user.email "${{ secrets.NPM_EMAIL }}";
-          echo "Hello $(git config --get user.name)";
-      - run: npm run build
-      - run: npm run test
+#       - run: rm -f ~/.npmrc ; rm -f ./.npmrc ; echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM2_TOKEN_PUB }}" > ./.npmrc
+#       - run: |
+#           git config user.name "${{ secrets.NPM_NAME }}";
+#           git config user.email "${{ secrets.NPM_EMAIL }}";
+#           echo "Hello $(git config --get user.name)";
+#       - run: npm run build
+#       - run: npm run test
 
-      - name: Test Report
-        uses: dorny/test-reporter@v1.5.0
-        with:
-          name: Tests
-          path: junit.json
-          reporter: mocha-json
+#       - name: Test Report
+#         uses: dorny/test-reporter@v1.5.0
+#         with:
+#           name: Tests
+#           path: junit.json
+#           reporter: mocha-json
 
-      # - run: npm test
-      - name: output version
-        run: |
-          echo "Setting version too: ${{ steps.semver.outputs.version }}";
-      - run: npm version ${{ steps.semver.outputs.version }}
-      - run: npm publish --tag rc
+#       # - run: npm test
+#       - name: output version
+#         run: |
+#           echo "Setting version too: ${{ steps.semver.outputs.version }}";
+#       - run: npm version ${{ steps.semver.outputs.version }}
+#       - run: npm publish --tag rc
 
-      #- name: Push tag
-      #  id: tag_version
-      #  uses: mathieudutour/github-tag-action@v6.0
-      #  with:
-      #    custom_tag: ${{ steps.semver.outputs.version }}
-      #    github_token: ${{ secrets.GITHUB_TOKEN }}
-      #- uses: ncipollo/release-action@v1
-      #  with:
-      #    tag: "v${{ steps.semver.outputs.version }}"
-      #    name: "v${{ steps.semver.outputs.version }}"
-      #    body: "See release: https://www.npmjs.com/package/@bettercorp/tools/v/${{ steps.semver.outputs.version }}"
-      #    token: ${{ secrets.GITHUB_TOKEN }}
+#       #- name: Push tag
+#       #  id: tag_version
+#       #  uses: mathieudutour/github-tag-action@v6.0
+#       #  with:
+#       #    custom_tag: ${{ steps.semver.outputs.version }}
+#       #    github_token: ${{ secrets.GITHUB_TOKEN }}
+#       #- uses: ncipollo/release-action@v1
+#       #  with:
+#       #    tag: "v${{ steps.semver.outputs.version }}"
+#       #    name: "v${{ steps.semver.outputs.version }}"
+#       #    body: "See release: https://www.npmjs.com/package/@bettercorp/tools/v/${{ steps.semver.outputs.version }}"
+#       #    token: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: cleanup
-        if: always()
-        run: rm -f ~/.npmrc ; rm -f ./.npmrc;
+#       - name: cleanup
+#         if: always()
+#         run: rm -f ~/.npmrc ; rm -f ./.npmrc;
 
-  buildDocsMaster:
-    runs-on: ubuntu-latest
+#   buildDocsMaster:
+#     runs-on: ubuntu-latest
 
-    strategy:
-      matrix:
-        node-version: [16.x]
-        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
+#     strategy:
+#       matrix:
+#         node-version: [16.x]
+#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-      - name: Use Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@v3
-        with:
-          node-version: ${{ matrix.node-version }}
-          cache: "npm"
-      - run: npm ci
-        working-directory: documentation/
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v3
+#         with:
+#           fetch-depth: 0
+#       - name: Use Node.js ${{ matrix.node-version }}
+#         uses: actions/setup-node@v3
+#         with:
+#           node-version: ${{ matrix.node-version }}
+#           cache: "npm"
+#       - run: npm ci
+#         working-directory: documentation/
 
-      - run: npm run build
-        working-directory: documentation/
+#       - run: npm run build
+#         working-directory: documentation/
 
-      - name: Update site
-        uses: cloudflare/wrangler-action@2.0.0
-        with:
-          apiToken: ${{ secrets.CF_API_TOKEN }}
-          accountId: ${{ secrets.CF_ACCOUNT_ID }}
-          command: pages publish documentation/.vuepress/dist --project-name=better-tools  --branch=rc
+#       - name: Update site
+#         uses: cloudflare/wrangler-action@2.0.0
+#         with:
+#           apiToken: ${{ secrets.CF_API_TOKEN }}
+#           accountId: ${{ secrets.CF_ACCOUNT_ID }}
+#           command: pages publish documentation/.vuepress/dist --project-name=better-tools  --branch=rc
